import './doriosAPI/main.js'
// import './durability.js'
import './tool_lock_memory.js'
import './gloves.js'
import './chisel.js'
import './glass_cutter.js'
import './furniture_hammer.js'
import './stairs.js'
import './variants.js'
import './insight_registry_injector.generated.js'

