import path from "node:path";
import {
  PROJECT_PATHS,
  countValues,
  duplicateGroups,
  groupBy,
  stableJson,
  scanProject,
  writeJson,
  writeText,
} from "./lib/project-index.mjs";

const project = await scanProject();
const blockDuplicates = duplicateGroups(project.blocks);
const recipeDuplicates = duplicateGroups(project.recipes);
const cullingDuplicates = duplicateGroups(project.culling);

const normalizedCulling = project.culling.map((entry) => {
  const document = structuredClone(entry.document);
  document["minecraft:block_culling_rules"].description.identifier = "normalized:culling";
  return { ...entry, normalizedSignature: stableJson(document) };
});

const cullingStructures = [...groupBy(normalizedCulling, (entry) => entry.normalizedSignature).values()]
  .map((entries) => ({
    count: entries.length,
    identifiers: entries.map((entry) => entry.identifier).sort((left, right) => left.localeCompare(right, "en")),
    files: entries.map((entry) => entry.file).sort((left, right) => left.localeCompare(right, "en")),
  }))
  .sort((left, right) => right.count - left.count);

function serializeDuplicate(group) {
  return {
    identifier: group.identifier,
    definitionCount: group.definitions.length,
    semanticVariantCount: group.semanticVariantCount,
    definitions: group.definitions.map((entry) => ({
      file: entry.file,
      formatVersion: entry.formatVersion,
      lightDampening: entry.components?.["minecraft:light_dampening"] ?? null,
    })),
  };
}

const report = {
  schemaVersion: 1,
  summary: {
    blockFiles: project.blocks.length,
    uniqueBlockIdentifiers: new Set(project.blocks.map((entry) => entry.identifier)).size,
    duplicateBlockIdentifiers: blockDuplicates.length,
    conflictingBlockIdentifiers: blockDuplicates.filter((group) => group.semanticVariantCount > 1).length,
    recipeFiles: project.recipes.length,
    uniqueRecipeIdentifiers: new Set(project.recipes.map((entry) => entry.identifier)).size,
    duplicateRecipeIdentifiers: recipeDuplicates.length,
    cullingFiles: project.culling.length,
    uniqueCullingIdentifiers: new Set(project.culling.map((entry) => entry.identifier)).size,
    uniqueCullingStructures: cullingStructures.length,
    parseErrors: project.parseErrors.length,
  },
  formatVersions: {
    blocks: countValues(project.blocks.map((entry) => entry.formatVersion)),
    recipes: countValues(project.recipes.map((entry) => entry.formatVersion)),
    culling: countValues(project.culling.map((entry) => entry.formatVersion)),
  },
  duplicateBlocks: blockDuplicates.map(serializeDuplicate),
  duplicateRecipes: recipeDuplicates.map(serializeDuplicate),
  duplicateCulling: cullingDuplicates.map(serializeDuplicate),
  cullingStructures,
  parseErrors: project.parseErrors,
};

const lines = [
  "# Content audit",
  "",
  "Generated by `npm run content:audit`. Do not edit this report manually.",
  "",
  "## Summary",
  "",
  "| Metric | Value |",
  "| --- | ---: |",
  ...Object.entries(report.summary).map(([key, value]) => `| ${key} | ${value} |`),
  "",
  "## Block format versions",
  "",
  "| Format | Files |",
  "| --- | ---: |",
  ...Object.entries(report.formatVersions.blocks).map(([key, value]) => `| ${key} | ${value} |`),
  "",
  "## Duplicate block identifiers",
  "",
  "| Identifier | Definitions | Semantic variants | light_dampening |",
  "| --- | ---: | ---: | --- |",
  ...report.duplicateBlocks.map((entry) => {
    const light = entry.definitions.map((definition) => `${definition.lightDampening ?? "unset"} (${definition.file})`).join("<br>");
    return `| ${entry.identifier} | ${entry.definitionCount} | ${entry.semanticVariantCount} | ${light} |`;
  }),
  "",
  "## Duplicate recipe identifiers",
  "",
  ...report.duplicateRecipes.map((entry) => `- ${entry.identifier}: ${entry.definitions.map((definition) => definition.file).join(", ")}`),
  "",
  "## Culling structures",
  "",
  ...report.cullingStructures.map((entry, index) => `- Structure ${index + 1}: ${entry.count} files`),
];

await writeJson(path.join(PROJECT_PATHS.generated, "content-audit.json"), report);
await writeText(path.join(PROJECT_PATHS.generated, "content-audit.md"), lines.join("\n"));

console.log(`Blocks: ${report.summary.blockFiles} files / ${report.summary.uniqueBlockIdentifiers} unique identifiers`);
console.log(`Recipes: ${report.summary.recipeFiles} files / ${report.summary.uniqueRecipeIdentifiers} unique identifiers`);
console.log(`Culling: ${report.summary.cullingFiles} files / ${report.summary.uniqueCullingStructures} unique structures`);
console.log("Reports: tools/generated/content-audit.{json,md}");
